// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzFKmW1k0Vv3cA6npPyAL5asQMUprGawg',
    appId: '1:194180896838:web:ccfaa5692d96f7c5a15247',
    messagingSenderId: '194180896838',
    projectId: 'libro-de-cocina-a7371',
    authDomain: 'libro-de-cocina-a7371.firebaseapp.com',
    storageBucket: 'libro-de-cocina-a7371.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVDfTvvLmNZt60eHd7JeczK20J6SK2X9A',
    appId: '1:194180896838:android:a1634d3a5e733404a15247',
    messagingSenderId: '194180896838',
    projectId: 'libro-de-cocina-a7371',
    storageBucket: 'libro-de-cocina-a7371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkekJbMm0evIOg7G_No-hna0JHfE7LIiI',
    appId: '1:194180896838:ios:0029c2028df4575ea15247',
    messagingSenderId: '194180896838',
    projectId: 'libro-de-cocina-a7371',
    storageBucket: 'libro-de-cocina-a7371.appspot.com',
    iosClientId: '194180896838-9vj1asnbm172442cbamf0v6ado93ev0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.libroCocina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkekJbMm0evIOg7G_No-hna0JHfE7LIiI',
    appId: '1:194180896838:ios:0029c2028df4575ea15247',
    messagingSenderId: '194180896838',
    projectId: 'libro-de-cocina-a7371',
    storageBucket: 'libro-de-cocina-a7371.appspot.com',
    iosClientId: '194180896838-9vj1asnbm172442cbamf0v6ado93ev0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.libroCocina',
  );
}
